version: "3"

services:
  persons:
    image: 'persons:latest'
    build:
      context: .
    container_name: persons
    depends_on:
      - persons-db
    ports:
      - "8080:8080"

  persons-db:
    image: postgres
    container_name: persons-db
    environment:
      - "POSTGRES_USER=myuser"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_DB=persons"
    ports:
      - "5435:5432"